FROM netboxcommunity/netbox:latest
# Creations of netbox_topology_views file path
RUN mkdir -p /opt/netbox/netbox/static/netbox_topology_views/img

COPY ./plugin_requirements.txt /opt/netbox/
RUN /opt/netbox/venv/bin/pip install  --no-warn-script-location -r /opt/netbox/plugin_requirements.txt

# These lines are only required if your plugin has its own static files.
COPY configuration/configuration.py /etc/netbox/config/configuration.py
COPY configuration/plugins.py /etc/netbox/config/plugins.py
RUN SECRET_KEY="dummydummydummydummydummydummydummydummydummydummy/dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input
# RUN /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py migrate